sudo: required
dist: trusty
group: deprecated-2017Q4

language: python

python:
- '2.7'

env:
    - CKANVERSION=2.7

services:
    - redis-server
    - postgresql

install:
    - bash bin/travis-build.bash

script: bin/travis-run.sh

after_success: coveralls
